### ISSUE TITLE
Add a rule to avoid a `sinon.assert.called()` followed by `sinon.assert.calledWith()`

### ISSUE THREAD

**Issue by willdurand** [mozilla/eslint-plugin-amo#3]
When we use `sinon.assert.calledWith()`, there is no need to have `sinon.assert.called()` before, it is implied with `calledWith()`.

```js
// BAD
const stub = sinon.spy();

sinon.assert.called(stub);
sinon.assert.calledWith(stub, params);
```

```js
// GOOD
const stub = sinon.spy();

sinon.assert.calledWith(stub, params);
```

**Comment by willdurand** [comment]
@kumar303 Do we want to avoid `calledOnce()` too?

```js
sinon.assert.calledOnce(stub);
sinon.assert.calledWith(stub, params);
```

I don't think we can write `calledOnceWith`, can w?

**Comment by kumar303** [comment]
Call counts need to be asserted independently from `calledWith()`, correct.

Personally, I'd prefer to see it in this order:

```js
sinon.assert.calledWith(stub, params);
sinon.assert.calledOnce(stub);
```

That way the first error is more informative in the case where `stub` is never called. It may not be worth adding a lint rule just for that, though.

**Comment by willdurand** [comment]
That makes sense, I'll open another issue for that then.
