### ISSUE TITLE
Add a rule to make sure `withRouter` HOC is the first in the list of `compose()`

### ISSUE THREAD

**Issue by willdurand** [mozilla/eslint-plugin-amo#9]
See: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md#important-note

```js
// BAD
connect(...)(withRouter(MyComponent))

compose(
  connect(...),
  withRouter
)(MyComponent)

// GOOD
withRouter(connect(...)(MyComponent))

compose(
  withRouter,
  connect(...)
)(MyComponent)
```

**Comment by RusinovAnton** [comment]
I would really like to have this rule in my project too. Is that even exists?

**Comment by willdurand** [comment]
@RusinovAnton no, not yet but that should be doable. Keep subscribed to this issue :)
